### ISSUE TITLE
Improve document title

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#1]
The first time I heard the title the thought that crossed my mind was that it could be used to support more modes of UDP usage that focus on listening - such as multicast reception.

However, when I look at the draft, the interaction model doesn't really fit the multicast subscribe/join model. (I can think of ways to do that but I won't waste your time here).

Assuming you want to keep the document scope and design as is, I might suggest a tweak to the document title that more closely matches that definition. Maybe something like "UDP socket multiplexing over single HTTP requests" :bike::shed"

**Comment by MikeBishop** [comment]
Listen seems reasonable, by comparison to existing syscalls. I suggest closing with no action, and revisit if the scope changes.

**Comment by asingh-g** [comment]
I think I should poll the WG if they want the name to change to connect-udp bind at the next IETF since that seemed to be the most popular name alternative from what I noticed in the mailing list.
