### ISSUE TITLE
Should "connect-udp-listen" be registered as "Connect-UDP-Listen"?

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#20]
Should "connect-udp-listen" be registered (and referred to in the text definition) as "Connect-UDP-Listen"? All of the registrations are in H1 capitalized style, so it feels like we should do that. Also useful to say if it is "Connect-UDP-Listen" or "Connect-Udp-Listen" canonically...

**Comment by asingh-g** [comment]
I don't have strong feelings either way, I would be willing to use H1 style. @DavidSchinazi thoughts?

**Comment by DavidSchinazi** [comment]
I couldn't find any official rules in the [style guide](https://httpwg.org/admin/editors/style-guide) but looking through the [IANA registry](https://www.iana.org/assignments/http-fields/http-fields.xhtml) I agree with Tommy that most fields are camel cased, with acronyms upper-cased. So I think we want to change this to `Connect-UDP-Listen`.
