### ISSUE TITLE
Allow peeling off connected connect-udp?

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#21]
As an alternative to compressing different contexts, we could also allow a client to open up a more standard "connect-udp" connected UDP socket through the proxy that shares a port with the listening "connect-udp" instance. That would allow a flow like:

1. Open listener connect-udp
2. Receive inbound packets (with IPs and ports in datagrams)
3. Open a more specific connect-udp for that IP and port, and continue without needing the datagrams to contain IP and port

This matches what technically is supported by sockets, where you can have an unconnected UDP socket in parallel with more specific connected UDP sockets.

**Comment by tfpauly** [comment]
I guess a problem here would be if the multiple requests end up on different hosts

**Comment by DavidSchinazi** [comment]
Yeah requests landing on different servers is a real problem. We could accomplish the same level of overhead without the separate request though, by using context IDs to compress the IP and port. Any reason that's not sufficient?

**Comment by tfpauly** [comment]
The only difference is that in the model of separate requests, you could close the listener and leave the more specific connection open. But that's probably not necessary to support, since you could also just drop packets you don't want to reply to.

**Comment by asingh-g** [comment]
If you want to close everything but the more specific connection, we can do what you proposed at last IETF about discarding uncompressed requests. I added it to the [PR for compression](https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp-listen/pull/19)
