### ISSUE TITLE
Appendix A mentions STUN server sending IP to other browser

### ISSUE THREAD

**Issue by recvfrom** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#25]
The example in Appendix A mentions:
> ... [the client] wishes to use WebRTC with another browser over a Bound UDP Proxying tunnel.  It contacts a STUN server at 192.0.2.42. The STUN server, in response, sends the proxy's IP address to the other browser at 203.0.113.33.  Using this information, the other browser sends a UDP packet to the proxy, which is proxied over HTTP back to the client.

IIUC the STUN server doesn't send information between clients, though, and instead is only used by each side to determine their public IP address when building the list of ICE candidates (which the clients then send to each other through other means).

**Comment by DavidSchinazi** [comment]
You're correct. OK we'll have to fix this. Marking as editorial.
