### ISSUE TITLE
Unclear validation requirement in Security Considerations

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#26]
From @gloinul on the [list](https://mailarchive.ietf.org/arch/msg/masque/vaL2o4FTvfzJMLYhBie1yIgNwbw/):

> Therefore, proxies MUST validate the target on every datagram and MUST NOT forward individual datagrams with unauthorized targets.

To me it is unclear what this sentence actually require the proxy to do? If one uses the uncompressed operation, the proxy can forward any arriving traffic to the client, equally the client can send with a target address of any. Is the expectation here to verify that the client is not sending any packets to a destination target that is on a list to be protected? How is the proxy arriving at which addresses are not ok to send to?

**Comment by DavidSchinazi** [comment]
I agree. This text predates the ability to close the uncompressed context, we just forgot to update it. Will fix

**Comment by asingh-g** [comment]
Closing this since #28 corrected this
