### ISSUE TITLE
Unclear discussion of context IDs

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-udp-listen#27]
From @gloinul on the [list](https://mailarchive.ietf.org/arch/msg/masque/vaL2o4FTvfzJMLYhBie1yIgNwbw/):

> Both client and proxy can then negotiate even and odd numbered context IDs to send UDP payloads to each other.

To me it is unclear what this sentence actually require the proxy to do? If one uses the uncompressed operation, the proxy can forward any arriving traffic to the client, equally the client can send with a target address of any. Is the expectation here to verify that the client is not sending any packets to a destination target that is on a list to be protected? How is the proxy arriving at which addresses are not ok to send to?

**Comment by DavidSchinazi** [comment]
The intent here was to remind the reader of how context IDs work per RFC 9298. We'll look into making some editorial improvements.

**Comment by asingh-g** [comment]
Closing this since #28 corrected this
